### ISSUE TITLE
Allow docker `recipe` property to be a string

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-community/containers-boshrelease#11]
Tried to do this perfectly reasonable thing this evening:

```
instance_groups:
  - name: what
    jobs:
      - name: docker
        release: containers
        properties:
          recipe: (( file "docker-compose.yml" ))
```

What I ended up with was a literal string, as a top-level YAML object, in docker-compose.yml, because the BOSH release does things with yaml emission.

If `recipe` is a string, we should just print it as-is, rather than re-YAML it.
