### ISSUE TITLE
ttar formatting of yaml documents

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/containers-boshrelease#5]
[`ttar` appears to be dissatisified with `yaml` content for `files`](https://github.com/cloudfoundry-community/containers-boshrelease/blob/master/src/ttar/ttar), formatting them with quotation marks and side arrows

given the following job properties in a deployment manifest:

```yml
...
    jobs:
      - name: docker
        release: containers
        properties:
          files:
            default.yml:
              splunk:
                role: splunk_standalone
                upgrade: false
```

this results in the following `default.yml` under `/var/vcap/jobs/docker/etc/running/default.yml`

```
{"splunk"=>{"role"=>"splunk_standalone", "upgrade"=>false}}
```

I was expecting the formatting of the generated `default.yml` to look like standard yml:

```yml
  splunk:
    role: splunk_standalone
    upgrade: false
```

this can be mitigated by inlining the yaml into the deployment manifest directly and putting a pipe char (`|`) in the deployment next to `default.yml`:

```yml
    jobs:
      - name: docker
        release: containers
        properties:
          files:
            default.yml: |
              splunk:
                role: splunk_standalone
                upgrade: false
```

which produces expected results under `/var/vcap/jobs/docker/etc/running/default.yml`:

```yml
splunk:
  role: splunk_standalone
  upgrade: false
```

But the pipe operator in the deployment manifest works by turning everything under it into a plain string. Which is _fine_, and for all intents and purposes deployments can be stretched to work. However, if someone tries to plop in `files` using `((variable_references))` or modify the `files` content via operators, it'll still break.

Any thoughts? Thanks for the time 👍
