### ISSUE TITLE
task for jumpbox fails

### ISSUE THREAD

**Issue by dhoffi** [cloudfoundry-community/containers-boshrelease#7]
Hi trying out the jumpbox manifest with:

```
- type: replace
  path: /instance_groups/name=docker/jobs/name=jumpbox/properties/hostname?
  value: jumpbox-containers.malbec.local.lab

- type: replace
  path: /instance_groups/name=docker/jobs/name=jumpbox/properties/users
  value:
    - username:  admin
      image: 'huntprod/cf-jumpbox:latest'
      shell: /bin/bash
      env: https://github.com/hoffipublic/jumpbox-boshrelease-env
      key: ssh-rsa AAAAB3N<snip>
```

```
$ nslookup jumpbox-containers.malbec.local.lab
Server:		192.168.100.1
Address:	192.168.100.1#53

Name:	jumpbox-containers.malbec.local.lab
Address: 10.0.2.241
```

but on `$ bosh -d jumpbox deploy manifests/jumpbox.yml -o ops/add-user-op.yml`

I get a bit stuck on:

```
Task 22

Task 22 | 11:30:22 | Preparing deployment: Preparing deployment (00:00:00)
Task 22 | 11:30:22 | Preparing deployment: Rendering templates (00:00:01)
Task 22 | 11:30:23 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 22 | 11:30:23 | Updating instance docker: docker/6b121a53-6af0-4b61-b6b8-2e471f8b77f1 (0) (canary) (00:00:16)
                   L Error: Action Failed get_task: Task aa97ec32-72b2-486b-5951-2ca5401f9d1f result: 1 of 1 pre-start scripts failed. Failed Jobs: jumpbox.
Task 22 | 11:30:39 | Error: Action Failed get_task: Task aa97ec32-72b2-486b-5951-2ca5401f9d1f result: 1 of 1 pre-start scripts failed. Failed Jobs: jumpbox.

Task 22 Started  Tue Feb  4 11:30:22 UTC 2020
Task 22 Finished Tue Feb  4 11:30:39 UTC 2020
Task 22 Duration 00:00:17
Task 22 error

Updating deployment:
  Expected task '22' to succeed but state is 'error'

Exit code 1
```

not knowing where to look now as the vm is not up at this point.

and starting it with `bosh -d jumpbox start docker/6b121a53-6af0-4b61-b6b8-2e471f8b77f1`

```
/var/vcap/jobs$ ll
total 12
drwxr-x---  2 root vcap 4096 Feb  4 13:04 ./
drwxr-xr-x 11 root root 4096 Feb  4 12:39 ../
lrwxrwxrwx  1 root root   67 Feb  4 13:04 docker -> /var/vcap/data/jobs/docker/98863b0a2df6f5e29d08ef32bdbee7a4fd6ed227/
```

there is no jumpbox job

any ideas?
